****************************;
* WITH OUTLIERS             ;
****************************;
PROC MEANS DATA=TRAIN1;
RUN;

* CREATE INTERACTION VARIABLES;
DATA TRAIN2;
	SET TRAIN1;
	CENT1 = (GRLIVAREA_LOG - 13.0183)*(N1 - 0.2610966);
	CENT2 = (GRLIVAREA_LOG - 13.0183)*(N2 - 0.1514360);

	CENT1_LOG = (GRLIVAREA_LOG - 2.5141431)*(N1 - 0.2610966);
	CENT2_LOG = (GRLIVAREA_LOG - 2.5141431)*(N2 - 0.1514360);

	GRCENT=(GRLIVAREA_LOG - 2.5141431);

RUN;

ODS GRAPHICS ON;

SYMBOL1 V='SQUAREFILLED' C="#58508D" I=NONE;
SYMBOL2 V='DOT' C=ROSE I=NONE;
SYMBOL3 V='TRIANGLEFILLED' C=BIOY I=NONE;
title;
*EDA AND REGRESSIONS WITHOUT TRANSFORMATIONS;
*PUT GRAPH IN REPORT;
PROC GPLOT DATA=TRAIN2;
PLOT SALEPRICE*GRLIVAREA=NEIGHBORHOOD;
TITLE1 'Figure 1: House Sales Price and Square Footage by Neighborhood';
TITLE2 'Without Transformations';
RUN;

PROC REG DATA=TRAIN2;
MODEL SALEPRICE = N1 N2 GRLIVAREA /VIF; 
TITLE 'REGULAR';
RUN;

PROC REG DATA=TRAIN2;
MODEL SALEPRICE = N1 N2 GRLIVAREA INT1 INT2/VIF;
TITLE 'NO TRANSFORMATION WITH INTERACTION';
RUN;

PROC REG DATA=TRAIN2;
MODEL SALEPRICE = N1 N2 GRLIVAREA CENT1 CENT2/VIF;
TITLE 'NO TRANSFORMATIONS WITH CENTERING INTERACTION';
RUN;


*EDA AND REGRESSIONS WITH TRANSFORMATIONS;
* PUT GRAPH IN REPORT;
PROC GPLOT DATA=TRAIN2;
PLOT SALEPRICE_LOG*GRLIVAREA_LOG=NEIGHBORHOOD;
TITLE1 'Figure 2: House Sales Price and Square Footage by Neighborhood';
TITLE2 'With Log Transformations';
RUN;

PROC REG DATA=TRAIN2;
	MODEL SALEPRICE = N1 N2 GRLIVAREA /VIF; 
	TITLE1 'Figure 4: Simple Linear Regression';
	TITLE2 'No Transformations';
RUN;


*THIS IS THE WINNING MODEL WITH OUTLIERS INCLUDED;
PROC REG DATA=TRAIN2 plots=all;
	MODEL SALEPRICE_LOG = N1 N2 GRLIVAREA_LOG CENT1_LOG CENT2_LOG/VIF; 
	TITLE1 'Figure 6: Simple Linear Regression';
	TITLE2 'Log-Log Transformation';
RUN;

*THIS IS THE GRAPH FOR THE WINNING MODEL WITH OUTLIERS INCLUDED;
PROC SGPLOT DATA=TRAIN2 ;
   TITLE "Sales Price by Living Area and Neighborhood";
   REG Y=SALEPRICE_LOG X=GRLIVAREA_LOG / GROUP=NEIGHBORHOOD ;
RUN;

****************************;
* WITHOUT OUTLIERS          ;
****************************;
DATA TRAIN_NO_OUTLIERS;
	SET TRAIN1;
	IF GRLIVAREA < 4000/100;
RUN;

PROC MEANS DATA=TRAIN_NO_OUTLIERS;
RUN;

DATA TRAIN_NO_OUTLIERS1;
	SET TRAIN_NO_OUTLIERS;
	CENT1 = (GRLIVAREA_LOG - 12.8158530)*(N1 - 0.2572178);
	CENT2 = (GRLIVAREA_LOG - 12.8158530)*(N2 - 0.1522310);

	CENT1_LOG = (GRLIVAREA_LOG - 2.5066639)*(N1 - 0.2572178);
	CENT2_LOG = (GRLIVAREA_LOG - 2.5066639)*(N2 - 0.1522310);
RUN;

SYMBOL1 V='SQUARE' C=BLACK I=NONE;
SYMBOL2 V='CIRCLE' C=RED I=NONE;
SYMBOL3 V='TRIANGLE' C=BLUE I=NONE;

PROC GPLOT DATA=TRAIN_NO_OUTLIERS1;
PLOT SALEPRICE * GRLIVAREA=NEIGHBORHOOD;
TITLE1 'Figure 7: House Sales Price and Square Footage by Neighborhood';
TITLE2 'Without Outliers, Without Transformations';
RUN;

PROC GPLOT DATA=TRAIN_NO_OUTLIERS1;
PLOT SALEPRICE_LOG * GRLIVAREA_LOG=NEIGHBORHOOD;
TITLE1 'Figure 8: House Sales Price and Square Footage by Neighborhood';
TITLE2 'Without Outliers, Without Log Transformations';
RUN;

PROC REG DATA=TRAIN_NO_OUTLIERS1 PLOTS=ALL;
MODEL SALEPRICE = N1 N2 GRLIVAREA /VIF;
TITLE1 'Figure 10: Simple Linear Regression';
TITLE2 'Without Outliers, Without Transformations';
RUN;

****************************;
* THIS IS THE MODEL WE WANT ;
****************************;
PROC REG DATA=TRAIN_NO_OUTLIERS1 PLOTS=ALL;
	MODEL SALEPRICE_LOG = N1 N2 GRLIVAREA_LOG CENT1_LOG CENT2_LOG/VIF CLB CLM CLI; /*VIF SHOULD BE BELOW 10, IDEALLY CLOSE TO 1*/
	TITLE1 'Figure 13: Linear Regression';
	TITLE2 'Without Outliers, Log-Log Transformations';
RUN;

*USE THIS GRAPH IN THE REPORT;
PROC SGPLOT DATA=TRAIN_NO_OUTLIERS1 ;
	TITLE "Sales Price by Living Area and Neighborhood";
	REG Y=SALEPRICE_LOG X=GRLIVAREA_LOG / GROUP=NEIGHBORHOOD ;
	TITLE1 'Figure 14: Linear Regression';
	TITLE2 'Without Outliers, Log-Log Transformations';
RUN;
