* DATA PREP;
DATA TRAIN2;
	SET TRAIN;

	SALEPRICE_LOG = LOG(SALEPRICE);

	IF GRLIVAREA < 4000;

	BATHROOMS = .5*HALFBATH + FULLBATH;
	ROOMS = BATHROOMS + TOTRMSABVGRD;

	SQFT = (BSMTFINSF1 + GRLIVAREA)/100;
	SQFT_LOG = LOG(SQFT);

	GRLIVAREA = GRLIVAREA/100;
	GRLIVAREA_LOG = LOG(GRLIVAREA);
RUN;

* CORRELATION MATRIX;
* CODE FROM HTTPS://BLOGS.SAS.COM/CONTENT/SASDUMMY/2013/06/12/CORRELATIONS-MATRIX-HEATMAP-WITH-SAS/;

%MACRO PREPCORRDATA(IN=,OUT=);
  /* RUN CORR MATRIX FOR INPUT DATA, ALL NUMERIC VARS */
  PROC CORR DATA=&IN. NOPRINT
    PEARSON
    OUTP=WORK._TMPCORR
    VARDEF=DF
  ;
  RUN;
 
  /* PREP DATA FOR HEAT MAP */
DATA &OUT.;
  KEEP X Y R;
  SET WORK._TMPCORR(WHERE=(_TYPE_="CORR"));
  ARRAY V{*} _NUMERIC_;
  X = _NAME_;
  DO I = DIM(V) TO 1 BY -1;
    Y = VNAME(V(I));
    R = V(I);
    /* CREATES A LOWER TRIANGULAR MATRIX */
    IF (I<_N_) THEN
      R=.;
    OUTPUT;
  END;
RUN;
 
PROC DATASETS LIB=WORK NOLIST NOWARN;
  DELETE _TMPCORR;
QUIT;
%MEND;

ODS PATH WORK.MYSTORE(UPDATE) SASHELP.TMPLMST(READ);
 
PROC TEMPLATE;
  DEFINE STATGRAPH CORRHEATMAP;
   DYNAMIC _TITLE;
    BEGINGRAPH;
      ENTRYTITLE _TITLE;
      RANGEATTRMAP NAME='MAP';
      RANGE -1 - 1 / RANGECOLORMODEL=(CXD8B365 CXF5F5F5 CX5AB4AC);
      ENDRANGEATTRMAP;
      RANGEATTRVAR VAR=R ATTRVAR=R ATTRMAP='MAP';
      LAYOUT OVERLAY / 
        XAXISOPTS=(DISPLAY=(LINE TICKS TICKVALUES)) 
        YAXISOPTS=(DISPLAY=(LINE TICKS TICKVALUES));
        HEATMAPPARM X = X Y = Y COLORRESPONSE = R / 
          XBINAXIS=FALSE YBINAXIS=FALSE
          NAME = "HEATMAP" DISPLAY=ALL;
        CONTINUOUSLEGEND "HEATMAP" / 
          ORIENT = VERTICAL LOCATION = OUTSIDE TITLE="PEARSON CORRELATION";
      ENDLAYOUT;
    ENDGRAPH;
  END;
RUN;

ODS GRAPHICS /HEIGHT=2400 WIDTH=2400 IMAGEMAP;

%PREPCORRDATA(IN=TRAIN2(DROP=ID) ,OUT=CORR_MATRIX);
PROC SGRENDER DATA=CORR_MATRIX TEMPLATE=CORRHEATMAP;
   DYNAMIC _TITLE_="CORR MATRIX";
   TITLE1 'FIGURE 15: CORRELATION MATRIX';
RUN;

* EDA FOR CATEGORICAL VARIABLES;
ODS GRAPHICS /HEIGHT=600 WIDTH=600 IMAGEMAP;

/*Panel with histograms and density plots*/
PROC SGPANEL DATA=TRAIN2 NOAUTOLEGEND;
	TITLE "Figure 16: Sales Price by Central Air";
	PANELBY CENTRALAIR;
	HISTOGRAM SALEPRICE_LOG;
	DENSITY SALEPRICE_LOG;
RUN;

PROC SGPANEL DATA=TRAIN2 NOAUTOLEGEND;
	TITLE "Figure 17: Sales Price by Building Type";
	PANELBY BldgType;
	HISTOGRAM SALEPRICE_LOG;
	DENSITY SALEPRICE_LOG;
RUN;

PROC SGPANEL DATA=TRAIN2(WHERE=(MISSING(ROOFMATL)=0)) NOAUTOLEGEND;
	TITLE "Figure 18: Sales Price by Roof Material";
	PANELBY ROOFMATL /COLUMNS=4;
	HISTOGRAM SALEPRICE_LOG;
RUN;

ODS GRAPHICS /HEIGHT=600 WIDTH=2400 IMAGEMAP;
PROC SGPANEL DATA=TRAIN2 NOAUTOLEGEND;
	TITLE "Figure 19: Sales Price by Neighborhood";
	PANELBY NEIGHBORHOOD / columns=13;
	HISTOGRAM SALEPRICE_LOG;
	DENSITY SALEPRICE_LOG;
RUN;

PROC GLMSELECT DATA=TRAIN2;
	CLASS EXTERQUAL BSMTQUAL KITCHENQUAL GARAGEFINISH GARAGETYPE HEATINGQC BSMTEXPOSURE LOTSHAPE GARAGECOND CENTRALAIR FOUNDATION NEIGHBORHOOD;
	MODEL SALEPRICE_LOG =  LOTAREA WOODDECKSF OPENPORCHSF  FIREPLACES MASVNRAREA  GARAGEYRBLT YEARBUILT 
		   ROOMS GARAGEAREA GARAGECARS OVERALLQUAL SQFT_LOG EXTERQUAL BSMTQUAL KITCHENQUAL GARAGEFINISH GARAGETYPE HEATINGQC BSMTEXPOSURE LOTSHAPE GARAGECOND CENTRALAIR FOUNDATION NEIGHBORHOOD
	  / SELECTION = FORWARD(STOP=CV) CVMETHOD=RANDOM(5) STATS=ADJRSQ;
	TITLE 'Figure 20: Forward Selection Model';
RUN;

PROC GLMSELECT DATA=TRAIN2;
	CLASS EXTERQUAL BSMTQUAL KITCHENQUAL GARAGEFINISH GARAGETYPE HEATINGQC BSMTEXPOSURE LOTSHAPE GARAGECOND CENTRALAIR FOUNDATION NEIGHBORHOOD;
	MODEL SALEPRICE_LOG =  LOTAREA WOODDECKSF OPENPORCHSF  FIREPLACES MASVNRAREA  GARAGEYRBLT YEARBUILT 
		   ROOMS GARAGEAREA GARAGECARS OVERALLQUAL SQFT_LOG EXTERQUAL BSMTQUAL KITCHENQUAL GARAGEFINISH GARAGETYPE HEATINGQC BSMTEXPOSURE LOTSHAPE GARAGECOND CENTRALAIR FOUNDATION NEIGHBORHOOD
	  / SELECTION = BACKWARD(STOP=CV) CVMETHOD=RANDOM(5) STATS=ADJRSQ;
	TITLE 'Figure 21: Backward Selection Model';
RUN;

PROC GLMSELECT DATA=TRAIN2;
	CLASS EXTERQUAL BSMTQUAL KITCHENQUAL GARAGEFINISH GARAGETYPE HEATINGQC BSMTEXPOSURE LOTSHAPE GARAGECOND CENTRALAIR FOUNDATION NEIGHBORHOOD;
	MODEL SALEPRICE_LOG =  LOTAREA WOODDECKSF OPENPORCHSF  FIREPLACES MASVNRAREA  GARAGEYRBLT YEARBUILT 
		   ROOMS GARAGEAREA GARAGECARS OVERALLQUAL SQFT_LOG EXTERQUAL BSMTQUAL KITCHENQUAL GARAGEFINISH GARAGETYPE HEATINGQC BSMTEXPOSURE LOTSHAPE GARAGECOND CENTRALAIR FOUNDATION NEIGHBORHOOD
	  / SELECTION = STEPWISE(STOP=CV) CVMETHOD=RANDOM(5) STATS=ADJRSQ;
	TITLE 'Figure 22: Stepwise Selection Model';
RUN;

ODS GRAPHICS ON;
* CUSTOM MODEL;
ODS GRAPHICS /HEIGHT=800 WIDTH=800 IMAGEMAP;
PROC GLM DATA=TRAIN2 PLOTS=ALL;
	CLASS NEIGHBORHOOD BLDGTYPE ROOFMATL CENTRALAIR;
	MODEL SALEPRICE_LOG = OVERALLQUAL OVERALLCOND YEARBUILT ROOFMATL BSMTFINSF1 TOTALBSMTSF GRLIVAREA_LOG CENTRALAIR NEIGHBORHOOD | BLDGTYPE / SOLUTION CLPARM ; 
	TITLE 'Figure 24: Custom Model Residual Plots';
RUN;

PROC GLMSELECT DATA=TRAIN2 PLOTS=ALL;
	CLASS NEIGHBORHOOD BLDGTYPE ROOFMATL CENTRALAIR;
	MODEL SALEPRICE_LOG = OVERALLQUAL OVERALLCOND YEARBUILT ROOFMATL BSMTFINSF1 TOTALBSMTSF GRLIVAREA_LOG CENTRALAIR NEIGHBORHOOD | BLDGTYPE / SELECTION=NONE;
RUN;
