%MACRO READ_DATA(PATH,NAME,NUM_OBS);
* REPLACE NA WITH MISSING;
DATA _NULL_;
	INFILE "&PATH.&NAME..csv" DSD TRUNCOVER;
	FILE "&PATH.&NAME._missing.csv" DSD;
	LENGTH WORD $200;
	
	* LOOP THROUGH EACH OF THE 81 COLUMNS AND REPLACE 'NA' WITH .;
	DO I=1 TO &NUM_OBS;
		INPUT WORD @;
		IF I IN (7,31,32,33,34,36,58,59,61,64,65,73,74,75) THEN DO;
			PUT WORD@;
		END;
		ELSE DO;
			IF WORD='NA' THEN WORD = .;
			PUT WORD@;
		END;
	END;
	
	* OUTPUT THE RECORD TO THE FILE;
	PUT;
RUN;

* IMPORT THE FILE WHERE NAs ARE REPLACED WITH .;
PROC IMPORT DATAFILE="&PATH.&NAME._missing.csv" OUT=&NAME REPLACE;
	GUESSINGROWS=MAX;
RUN;
%MEND;

* CREATE A DATASET WITH THE LIST OF FILES TO READ IN;
DATA LIST;
	* THIS IS WHERE YOU UPDATE WITH THE LOCATION OF YOUR FILES;
	PATH='/data/bnsf/ib/hubops/jford/data_science/kaggle/';
	NAME='train'; NUM_OBS = 81; OUTPUT;
	NAME='test'; NUM_OBS = 80; OUTPUT;
RUN;

* EXECUTE THE MACRO TO LOOP THROUGH THE FILES BEING READ IN;
DATA _NULL_;
	SET LIST;
    CALL EXECUTE('%READ_DATA('||PATH||','||NAME||','||NUM_OBS||')');
RUN;

* CREATE DUMMY VARIABLES FOR NEIGHBORHOOD AND ONLY KEEP 3 NEIGHBORHOODS;
DATA TRAIN1;
	SET TRAIN;
	IF NEIGHBORHOOD IN ('Edwards','BrkSide','NAmes');
	IF NEIGHBORHOOD = 'Edwards' THEN DO;
		N1=1; 
		N2=0;
	END;

	ELSE IF NEIGHBORHOOD = 'BrkSide' THEN DO;
		N1=0;
		N2=1;
	END;

	ELSE DO;
		N1=0;
		N2=0;
	END;

	GRLIVAREA = GRLIVAREA/100;

	SALEPRICE_LOG = LOG(SALEPRICE);
	GRLIVAREA_LOG = LOG(GRLIVAREA);
RUN;
