DATA TEST2;
	SET TEST;

	GRLIVAREA = GRLIVAREA/100;
	GRLIVAREA_LOG = LOG(GRLIVAREA);

RUN;

DATA KAGGLE;
SET TRAIN2 TEST2;
RUN;

PROC GLMSELECT DATA=KAGGLE;
CLASS EXTERQUAL BSMTQUAL KITCHENQUAL GARAGEFINISH GARAGETYPE HEATINGQC BSMTEXPOSURE LOTSHAPE GARAGECOND CENTRALAIR FOUNDATION NEIGHBORHOOD;
MODEL SALEPRICE_LOG =  LOTAREA HALFBATH '2NDFLRSF'N WOODDECKSF OPENPORCHSF  FIREPLACES MASVNRAREA BSMTFINSF1 GARAGEYRBLT YEARBUILT 
	  TOTRMSABVGRD FULLBATH '1STFLRSF'N GARAGEAREA TOTALBSMTSF GARAGECARS GRLIVAREA_LOG OVERALLQUAL
	  | EXTERQUAL BSMTQUAL KITCHENQUAL GARAGEFINISH GARAGETYPE HEATINGQC BSMTEXPOSURE LOTSHAPE GARAGECOND CENTRALAIR FOUNDATION
  / SELECTION = FORWARD(STOP=CV) CVMETHOD=RANDOM(5) STATS=ADJRSQ;
OUTPUT OUT=RESULTS P=PREDICT;
RUN;

DATA RESULTS2;
SET RESULTS;
IF ID > 1460;
SALEPRICE = EXP(PREDICT);
KEEP ID SALEPRICE;
RUN;

PROC EXPORT DATA=RESULTS2
FILE="/data/bnsf/ib/hubops/jford/data_science/kaggle/testResults.csv";
RUN;

