* KAGGLE SUBMISSIONS;
DATA TEST2;
	SET TEST;

	SALEPRICE_LOG = LOG(SALEPRICE);

	BATHROOMS = .5*HALFBATH + FULLBATH;
	ROOMS = BATHROOMS + TOTRMSABVGRD;

	SQFT = (BSMTFINSF1 + GRLIVAREA)/100;
	SQFT_LOG = LOG(SQFT);

	GRLIVAREA = GRLIVAREA/100;
	GRLIVAREA_LOG = LOG(GRLIVAREA);
RUN;

* COMBINE TRAIN AND TEST DATASETS;
DATA KAGGLE;
	SET TRAIN2 TEST2;
RUN;

* CALCULATE MEAN BY NEIGHBORHOOD FOR ANY MISSING PREDICTIONS;
PROC SQL;
	CREATE TABLE MEAN_PRICE AS
	SELECT NEIGHBORHOOD
	      ,AVG(SALEPRICE)
	FROM TRAIN2
	GROUP BY 1
	;
QUIT;

* FORWARD SELECTION MODEL;
PROC GLMSELECT DATA=KAGGLE;
	CLASS EXTERQUAL BSMTQUAL KITCHENQUAL GARAGEFINISH GARAGETYPE HEATINGQC BSMTEXPOSURE LOTSHAPE GARAGECOND CENTRALAIR FOUNDATION NEIGHBORHOOD;
	MODEL SALEPRICE_LOG =  LOTAREA WOODDECKSF OPENPORCHSF  FIREPLACES MASVNRAREA  GARAGEYRBLT YEARBUILT 
		   ROOMS GARAGEAREA GARAGECARS OVERALLQUAL SQFT_LOG EXTERQUAL BSMTQUAL KITCHENQUAL GARAGEFINISH GARAGETYPE HEATINGQC BSMTEXPOSURE LOTSHAPE GARAGECOND CENTRALAIR FOUNDATION NEIGHBORHOOD
	  / SELECTION = FORWARD(STOP=CV) CVMETHOD=RANDOM(5) STATS=ADJRSQ;
	 OUTPUT OUT=RESULTS_FORWARD P=PREDICT;
RUN;

* BACKWARD SELECTION MODEL;
PROC GLMSELECT DATA=KAGGLE;
	CLASS EXTERQUAL BSMTQUAL KITCHENQUAL GARAGEFINISH GARAGETYPE HEATINGQC BSMTEXPOSURE LOTSHAPE GARAGECOND CENTRALAIR FOUNDATION NEIGHBORHOOD;
	MODEL SALEPRICE_LOG =  LOTAREA WOODDECKSF OPENPORCHSF  FIREPLACES MASVNRAREA  GARAGEYRBLT YEARBUILT 
		   ROOMS GARAGEAREA GARAGECARS OVERALLQUAL SQFT_LOG EXTERQUAL BSMTQUAL KITCHENQUAL GARAGEFINISH GARAGETYPE HEATINGQC BSMTEXPOSURE LOTSHAPE GARAGECOND CENTRALAIR FOUNDATION NEIGHBORHOOD
	  / SELECTION = BACKWARD(STOP=CV) CVMETHOD=RANDOM(5) STATS=ADJRSQ;
	OUTPUT OUT=RESULTS_BACKWARD P=PREDICT;
RUN;

* STEPWISE SELECTION MODEL;
PROC GLMSELECT DATA=KAGGLE;
	CLASS EXTERQUAL BSMTQUAL KITCHENQUAL GARAGEFINISH GARAGETYPE HEATINGQC BSMTEXPOSURE LOTSHAPE GARAGECOND CENTRALAIR FOUNDATION NEIGHBORHOOD;
	MODEL SALEPRICE_LOG =  LOTAREA WOODDECKSF OPENPORCHSF  FIREPLACES MASVNRAREA  GARAGEYRBLT YEARBUILT 
		   ROOMS GARAGEAREA GARAGECARS OVERALLQUAL SQFT_LOG EXTERQUAL BSMTQUAL KITCHENQUAL GARAGEFINISH GARAGETYPE HEATINGQC BSMTEXPOSURE LOTSHAPE GARAGECOND CENTRALAIR FOUNDATION NEIGHBORHOOD
	  / SELECTION = STEPWISE(STOP=CV) CVMETHOD=RANDOM(5) STATS=ADJRSQ;
	OUTPUT OUT=RESULTS_STEPWISE P=PREDICT;
RUN;

* CUSTOM MODEL;
PROC GLMSELECT DATA=kaggle PLOTS=ALL;
	CLASS NEIGHBORHOOD BLDGTYPE ROOFMATL CENTRALAIR;
	MODEL SALEPRICE_LOG = OVERALLQUAL OVERALLCOND YEARBUILT ROOFMATL BSMTFINSF1 TOTALBSMTSF GRLIVAREA_LOG CENTRALAIR NEIGHBORHOOD | BLDGTYPE / SELECTION=NONE CVMETHOD=RANDOM(5) stats=press;
	OUTPUT OUT=RESULTS_CUSTOM P=PREDICT;
RUN;

%MACRO FILE_SUBMISSION(FILE);
DATA RESULTS2;
SET &FILE;
IF ID > 1460;
SALEPRICE = EXP(PREDICT);

* REPLACE ANY MISSING PREDICTIONS WITH THE MEAN SALES PRICE FOR THE NEIGHBORHOOD;
if missing(predict) = 1 then do;
if neighborhood = "Blmngtn" then saleprice=	194870.8824;
else if neighborhood = "Blueste" then saleprice=137500;
else if neighborhood = "BrDale" then saleprice=	104493.75;
else if neighborhood = "BrkSide" then saleprice=124834.0517;
else if neighborhood = "ClearCr" then saleprice=212565.4286;
else if neighborhood = "CollgCr" then saleprice=197965.7733;
else if neighborhood = "Crawfor" then saleprice=210624.7255;
else if neighborhood = "Edwards" then saleprice=127318.5714;
else if neighborhood = "Gilbert" then saleprice=192854.5063;
else if neighborhood = "IDOTRR" then saleprice=	100123.7838;
else if neighborhood = "MeadowV" then saleprice=98576.47059;
else if neighborhood = "Mitchel" then saleprice=156270.1225;
else if neighborhood = "NAmes" then saleprice=	145847.08;
else if neighborhood = "NPkVill" then saleprice=142694.4444;
else if neighborhood = "NWAmes" then saleprice=	189050.0685;
else if neighborhood = "NoRidge" then saleprice=314028.4103;
else if neighborhood = "NridgHt" then saleprice=316270.6234;
else if neighborhood = "OldTown" then saleprice=128225.3009;
else if neighborhood = "SWISU" then saleprice=	142591.36;
else if neighborhood = "Sawyer" then saleprice=	136793.1351;
else if neighborhood = "SawyerW" then saleprice=186555.7966;
else if neighborhood = "Somerst" then saleprice=225379.8372;
else if neighborhood = "StoneBr" then saleprice=310499;
else if neighborhood = "Timber" then saleprice=	242247.4474;
else if neighborhood = "Veenker" then saleprice=238772.7273;
end;

KEEP ID SALEPRICE;
RUN;

PROC EXPORT DATA=RESULTS2
FILE="/data/bnsf/ib/hubops/jford/data_science/kaggle/&FILE..csv" replace;
RUN;
%MEND;

DATA LIST;
	LENGTH FILE $16.;
	FILE="RESULTS_FORWARD"; OUTPUT;
	FILE="RESULTS_BACKWARD"; OUTPUT;
	FILE="RESULTS_STEPWISE"; OUTPUT;
	FILE="RESULTS_CUSTOM"; OUTPUT;
RUN;

DATA _NULL_;
	SET LIST;
    CALL EXECUTE('%FILE_SUBMISSION('||FILE||')');
RUN;

